name: Migrate Data
on:
  push:
    branches: main
    paths:
      - "migrations/**"
      - ".github/workflows/migrations.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_AWS_ACCESS_SECRET }}
  AWS_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  DATABASE_URL: mysql://clarity_davidvargas_me:${{ secrets.MYSQL_PASSWORD }}@vargas-arts.c2sjnb5f4d57.us-east-1.rds.amazonaws.com:5432/clarity_davidvargas_me
  IS_PRODUCTION: 1
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: Install NPM 8
        run: npm install -g npm@latest
      - name: install
        run: npm install
      - name: migrate
        run: npx fuego migrate
